name: publish to nuget

on:
  workflow_dispatch:
  push:
    branches:
      - main # Default release branch

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: src/DotEventOutbox/DotEventOutbox.csproj
      ARTIFACTS_PATH: ./artifacts

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.100"

      # Restore dependencies and build project
      - name: Restore and Build
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      # Run tests if any

      # Package
      - name: Package
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-build -o ${{ env.ARTIFACTS_PATH }}

      # Publish
      - name: Publish
        run: dotnet nuget push ${{ env.ARTIFACTS_PATH }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
